project:
  type: website
  output-dir: docs

website:
  title: "Raschka_youtube"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - AI Engineering.qmd

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true



