project:
  type: website
  output-dir: docs

website:
  title: "Articial Intelligence"
  page-footer: "Made by Edward F. Hillenaar with Quarto, Github pages and Netlify"
  navbar:
    title: Edward F. Hillenaar
    right:
      - href: LLM_building.qmd
        text: LLM building
      - href: AI Engineering.qmd
        text: AI Engineering
      - href: blog/index.qmd
      - contact.qmd
    tools:
      - icon: github
        href: https://github.com/EdwardHill15/Raschka_youtube

format:
  html:
    backgroundcolor: "#e8f4f8"
    theme: zephyr
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "darkblue"
    linkcolor: "blue"
    monofont: courier new



