project:
  type: website
  output-dir: docs

website:
  title: "Articial Intelligence"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: LLM_building.qmd
        text: LLM building
      - href: AI Engineering.qmd
        text: AI Engineering

format:
  html:
    theme: zephyr
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new



